id: issueCommentManagement.issueCommentOpened
name: GitOps.issueCommentManagement
description: Handlers for when an issue comment is first opened
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: "[Issue Management] Add needs attention label to issue if there is a new comment by a non-member"
        if:
          - payloadType: Issue_Comment
          - and:
            - isOpen
            - isIssue
            - not:
                or:
                  - hasLabel:
                      label: needs attention
                  - activitySenderHasPermission:
                      permission: write
                  - activitySenderHasPermission:
                      permission: admin
                  - isActivitySender:
                      user: msftbot[bot]
                      issueAuthor: False
                  - isActivitySender:
                      user: microsoft-github-policy-service[bot]
                      issueAuthor: False
                  - isActivitySender:
                      user: github-actions[bot]
                      issueAuthor: False
        then:
          - addLabel:
              label: needs attention
      - description: "[Issue Management] Remove needs attention label if there is a new comment by a member"
        if:
          - payloadType: Issue_Comment
          - and:
            - isOpen
            - isIssue
            - hasLabel:
                label: needs attention
            - or:
                - activitySenderHasPermission:
                    permission: write
                - activitySenderHasPermission:
                    permission: admin
        then:
          - removeLabel:
              label: needs attention